# Generated by Django 6.0.2 on 2026-07-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aquestion',
            options={'ordering': ['order'], 'verbose_name': 'Pregunta de institucionalización', 'verbose_name_plural': 'Preguntas de institucionalización'},
        ),
        migrations.AddField(
            model_name='aquestion',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
