# Generated by Django 6.0.2 on 2026-07-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_aquestion_options_aquestion_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planquestion',
            options={'ordering': ['order'], 'verbose_name': 'Pregunta de planes', 'verbose_name_plural': 'Preguntas de planes'},
        ),
        migrations.AddField(
            model_name='planquestion',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
