# Generated by Django 6.0.2 on 2026-08-12 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0009_remove_generalgroup_fields_generalgroup_instruction_and_more'),
        ('question', '0003_alter_planquestion_options_planquestion_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Clave interna')),
                ('text', models.TextField(verbose_name='Pregunta')),
                ('hint', models.TextField(blank=True, verbose_name='Texto de ayuda')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Rótulo del campo')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unidad')),
                ('q_type', models.CharField(choices=[('integer', 'Número entero'), ('boolean', 'Sí / No')], default='integer', max_length=10, verbose_name='Tipo de respuesta')),
                ('order', models.IntegerField(default=0)),
                ('addl_config', models.JSONField(blank=True, default=dict)),
                ('general_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='indicator.generalgroup')),
            ],
            options={
                'verbose_name': 'Pregunta general (Información de base)',
                'verbose_name_plural': 'Preguntas generales (Información de base)',
                'ordering': ['order'],
                'unique_together': {('general_group', 'name')},
            },
        ),
    ]
