# Generated by Django 6.0.2 on 2026-09-08 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0009_remove_generalgroup_fields_generalgroup_instruction_and_more'),
        ('question', '0004_generalquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiontype',
            options={'ordering': ['order'], 'verbose_name': 'Tipo de preguntas', 'verbose_name_plural': 'Tipos de preguntas'},
        ),
        migrations.AddField(
            model_name='questiontype',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden del bloque'),
        ),
        migrations.AddField(
            model_name='questiontype',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Aplica a todo observable'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='default_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ponderación por defecto'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Clave interna'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='public_name',
            field=models.CharField(max_length=150, verbose_name='Nombre público'),
        ),
        migrations.CreateModel(
            name='ObservableQuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ponderación')),
                ('observable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_weights', to='indicator.observable')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observable_weights', to='question.questiontype')),
            ],
            options={
                'verbose_name': 'Ponderación por tipo de pregunta',
                'verbose_name_plural': 'Ponderaciones por tipo de pregunta',
                'ordering': ['question_type__order'],
                'unique_together': {('observable', 'question_type')},
            },
        ),
        migrations.AddField(
            model_name='questiontype',
            name='observables',
            field=models.ManyToManyField(blank=True, related_name='question_types', through='question.ObservableQuestionType', to='indicator.observable'),
        ),
    ]
