# Generated by Django 6.0.2 on 2026-09-08 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_seed_observable_question_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aoption',
            options={'verbose_name': 'Opción de respuesta de armonización e institucionalización', 'verbose_name_plural': 'Opciones de respuesta de armonización e institucionalización'},
        ),
        migrations.AlterModelOptions(
            name='aquestion',
            options={'ordering': ['order'], 'verbose_name': 'Pregunta de armonización e institucionalización', 'verbose_name_plural': 'Preguntas de armonización e institucionalización'},
        ),
        migrations.AlterModelOptions(
            name='bquestion',
            options={'verbose_name': 'Pregunta de transversalidad orgánica', 'verbose_name_plural': 'Preguntas de transversalidad orgánica'},
        ),
        migrations.AlterModelOptions(
            name='reachquestion',
            options={'verbose_name': 'Pregunta de transversalidad sectorial', 'verbose_name_plural': 'Preguntas de transversalidad sectorial'},
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='weight_name',
        ),
    ]
