# Generated by Django 6.0.2 on 2026-09-08 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_alter_aoption_options_alter_aquestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontype',
            name='observables',
        ),
    ]
