# Generated by Django 6.0.2 on 2026-09-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_remove_questiontype_observables'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_open', models.BooleanField(default=True, verbose_name='Cuestionario abierto a edición')),
                ('seeded_at', models.DateTimeField(blank=True, null=True, verbose_name='Última siembra')),
            ],
            options={
                'verbose_name': 'Ajustes del cuestionario',
                'verbose_name_plural': 'Ajustes del cuestionario',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='questiontype',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='questiontype',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='bquestion',
            name='includes_academic',
            field=models.BooleanField(blank=True, null=True, verbose_name='Incluye instancias académicas'),
        ),
        migrations.AlterField(
            model_name='bquestion',
            name='includes_admin',
            field=models.BooleanField(blank=True, null=True, verbose_name='Incluye instancias administrativas'),
        ),
    ]
