# Generated by Django 6.0.2 on 2026-05-26 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_alter_goodpracticepackage_options_and_more'),
        ('ies', '0008_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodpractice',
            name='status_sending',
            field=models.ForeignKey(blank=True, default='draft', null=True, on_delete=django.db.models.deletion.CASCADE, to='ies.statuscontrol'),
        ),
    ]
