# Generated by Django 6.0.2 on 2026-06-11 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_alter_goodpractice_status_sending'),
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodpractice',
            name='status',
            field=models.ForeignKey(blank=True, default='bp_draft', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='flow.status'),
        ),
        migrations.AddField(
            model_name='goodpracticepackage',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='flow.status'),
        ),
    ]
