# Generated by Django 6.0.2 on 2026-09-22 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0008_goodpractice_status_goodpracticepackage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodpractice',
            name='status_sending',
        ),
        migrations.RemoveField(
            model_name='goodpracticepackage',
            name='status_sending',
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
    ]
