# Generated by Django 6.0.2 on 2026-10-03 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0009_remove_goodpractice_status_sending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodpractice',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='goodpracticepackage',
            name='comments',
        ),
    ]
