# Generated by Django 6.0.2 on 2026-08-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_observableresponse_axis_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupAttachment',
        ),
    ]
