# Generated by Django 6.0.2 on 2026-09-22 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0004_delete_groupattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observablecomment',
            name='observable_response',
        ),
        migrations.RemoveField(
            model_name='observablecomment',
            name='status_register',
        ),
        migrations.RemoveField(
            model_name='observablecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupresponse',
            name='status_register',
        ),
        migrations.RemoveField(
            model_name='observableresponse',
            name='status_register',
        ),
        migrations.DeleteModel(
            name='GroupComment',
        ),
        migrations.DeleteModel(
            name='ObservableComment',
        ),
    ]
