# Generated by Django 6.0.2 on 2026-09-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0005_remove_observablecomment_observable_response_and_more'),
        ('flow', '0009_attachment_is_public'),
        ('indicator', '0011_observable_note'),
        ('question', '0010_new_default_weights_and_type_icons'),
        ('survey', '0011_remove_axisvalue_status_register_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupresponse',
            constraint=models.UniqueConstraint(fields=('observable_response', 'question_type'), name='unique_group_response_per_type'),
        ),
        migrations.AddConstraint(
            model_name='observableresponse',
            constraint=models.UniqueConstraint(fields=('survey', 'observable'), name='unique_observable_response_per_survey'),
        ),
    ]
