# Generated by Django 6.0.2 on 2026-09-28 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0006_cp_capture'),
        ('indicator', '0011_observable_note'),
        ('question', '0011_questiontype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='question.aquestion'),
        ),
        migrations.AlterField(
            model_name='aresponse',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='a_responses', to='question.aoption'),
        ),
        migrations.AlterField(
            model_name='bresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='question.bquestion'),
        ),
        migrations.AlterField(
            model_name='groupresponse',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_responses', to='question.questiontype'),
        ),
        migrations.AlterField(
            model_name='observableresponse',
            name='observable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='indicator.observable'),
        ),
        migrations.AlterField(
            model_name='planresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.planquestion'),
        ),
        migrations.AlterField(
            model_name='reachresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='question.reachquestion'),
        ),
        migrations.AlterField(
            model_name='specialresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='question.specialquestion'),
        ),
    ]
