# Generated by Django 6.0.2 on 2026-10-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0007_protect_instrument_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='planresponse',
            name='technical_plans',
            field=models.IntegerField(blank=True, null=True, verbose_name='Planes de nivel técnico superior'),
        ),
    ]
