# Generated by Django 6.0.2 on 2026-07-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_generalgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='observable',
            name='reach_instances_question',
            field=models.TextField(blank=True, null=True, verbose_name='Pregunta de instancias (alcance)'),
        ),
    ]
