# Generated by Django 6.0.2 on 2026-07-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0005_observable_reach_instances_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observable',
            options={'ordering': ['order'], 'verbose_name': 'Observable (Pregunta inicial)', 'verbose_name_plural': 'Observables (Preguntas iniciales)'},
        ),
        migrations.AddField(
            model_name='observable',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sector',
            name='is_authority',
            field=models.BooleanField(default=False, verbose_name='Es autoridad'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
