# Generated by Django 6.0.2 on 2026-08-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0007_normalize_observable_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalgroup',
            options={'ordering': ['order'], 'verbose_name': 'Grupo de preguntas (Generales)', 'verbose_name_plural': 'Grupos de preguntas (Generales)'},
        ),
        migrations.AddField(
            model_name='generalgroup',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden en el cuestionario'),
        ),
        migrations.AddField(
            model_name='sector',
            name='is_ies_head',
            field=models.BooleanField(default=False, verbose_name='Es titular de la IES'),
        ),
        migrations.AddField(
            model_name='sector',
            name='is_standard_extra',
            field=models.BooleanField(default=False, verbose_name='Es población extra del estándar'),
        ),
    ]
