# Generated by Django 6.0.2 on 2026-08-12 08:11

from django.db import migrations, models

# Textos de encabezado de los 5 grupos, copiados de
# question/seed_data/catalogs.py. Van en duro y no importados: producción
# ya tiene las filas creadas, así que `load_questionnaire` —que solo los
# siembra al crear— nunca se las escribiría, y una migración que importa
# código del seed se rompe en cuanto ese código cambia.
GROUP_TEXTS = {
    "forma_gobierno": {
        "title": "Forma de gobierno",
    },
    "estructuras": {
        "title": "Estructuras",
    },
    "poblaciones": {
        "title": "Poblaciones",
        "subtitle": "Señale las poblaciones que integran a la comunidad "
                    "de su institución, así como todas aquellas que están "
                    "presentes física o virtualmente y con las que "
                    "mantiene vínculos a través de sus actividades "
                    "institucionales.",
        "instruction": "Para cada población marcada, indique cuántas "
                       "personas la integran según su sexo y género. Si "
                       "no cuenta con el dato exacto, registre su mejor "
                       "estimación.",
    },
    "autoridades": {
        "title": "Autoridades",
        "instruction": "Indique cuántas personas integran, según su sexo "
                       "y género, cada uno de los siguientes órganos y "
                       "conjuntos de autoridades de su institución.",
    },
    "planes_estudio": {
        "title": "Planes de estudio",
    },
}


def backfill_group_texts(apps, schema_editor):
    """Escribe los textos de encabezado en los grupos ya existentes.

    Solo toca lo que esté vacío: los componentes soltaron sus textos en
    duro y sin esto producción quedaría con encabezados en blanco, pero
    la redacción que el cliente ya haya editado no se pisa.
    """
    GeneralGroup = apps.get_model('indicator', 'GeneralGroup')
    for group in GeneralGroup.objects.filter(name__in=GROUP_TEXTS):
        changed = []
        for field, text in GROUP_TEXTS[group.name].items():
            if not getattr(group, field, ""):
                setattr(group, field, text)
                changed.append(field)
        if changed:
            group.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0008_alter_generalgroup_options_generalgroup_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalgroup',
            name='fields',
        ),
        migrations.AddField(
            model_name='generalgroup',
            name='instruction',
            field=models.TextField(blank=True, verbose_name='Instrucción para la IES'),
        ),
        migrations.AddField(
            model_name='generalgroup',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='generalgroup',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título del bloque'),
        ),
        migrations.RunPython(
            backfill_group_texts, migrations.RunPython.noop),
    ]
