# Generated by Django 6.0.2 on 2026-09-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    # Las columnas se van solo después de que la migración de datos
    # de `question` las copió a la tabla puente.
    dependencies = [
        ('question', '0006_seed_observable_question_types'),
        ('indicator', '0009_remove_generalgroup_fields_generalgroup_instruction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observable',
            name='a_weight',
        ),
        migrations.RemoveField(
            model_name='observable',
            name='b_weight',
        ),
        migrations.RemoveField(
            model_name='observable',
            name='plan_weight',
        ),
        migrations.RemoveField(
            model_name='observable',
            name='pop_weight',
        ),
        migrations.RemoveField(
            model_name='observable',
            name='reach_instances_question',
        ),
        migrations.RemoveField(
            model_name='observable',
            name='reach_weight',
        ),
        migrations.RemoveField(
            model_name='observable',
            name='special_weight',
        ),
        migrations.AlterField(
            model_name='observable',
            name='a_main_question',
            field=models.TextField(blank=True, null=True, verbose_name='Pregunta de armonización e institucionalización'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='a_main_subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Subtítulo de armonización e institucionalización'),
        ),
    ]
