# Generated by Django 6.0.2 on 2026-09-22 19:00

from django.db import migrations, models

# Texts of the «Nota:» paragraphs of vf-2025-ONIGIES-maquetado.docx,
# without the label; the export adds it back.
INITIAL_NOTES = {
    '1.2': (
        'No son aplicables los documentos de planeación, mismos que se '
        'reportan en otro apartado.'),
    '1.3': (
        'No se considerarán para esta pregunta:\n'
        '- Norma máxima reportada en la pregunta anterior.\n'
        '- Normas generales que sólo tengan una mención a la igualdad\n'
        '- Normas en materia de violencia de género\n'
        '- Manuales, guías, o documentos de referencia sin observancia '
        'jurídica'),
    '3.1': (
        'Se consideran políticas para la corresponsabilidad de los '
        'cuidados que son adicionales a las presentes en los contratos '
        'colectivos de trabajo, y que impactan en la comunidad académica '
        'sin relaciones laborales con la IES'),
}


def set_initial_notes(apps, schema_editor):
    # update() on a filter: a missing observable (empty test DB) is a
    # no-op, and a note already written from the dashboard is kept.
    Observable = apps.get_model('indicator', 'Observable')
    for number, note in INITIAL_NOTES.items():
        Observable.objects.filter(
            number=number, note__isnull=True).update(note=note)


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0010_remove_observable_a_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observable',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Nota'),
        ),
        migrations.RunPython(set_initial_notes, migrations.RunPython.noop),
    ]
