# Generated by Django 6.0.2 on 2026-06-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='level',
            field=models.CharField(choices=[('primary', 'Colección principal'), ('secondary', 'Colección secundaria'), ('relational', 'Colección relacional'), ('category_group', 'Grupo de categorías'), ('category_type', 'Tipo de categoría'), ('category_subtype', 'Subtipo de categoría')], max_length=40, verbose_name='Nivel'),
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['order'], 'verbose_name': 'Colección', 'verbose_name_plural': '1.1 Colecciones'},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='all_filters',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='app_label',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='available_actions',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='cat_params',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='open_insertion',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='optional_category',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='plural_name',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='sort_fields',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='xls_export',
        ),
        migrations.DeleteModel(
            name='FilterGroup',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
