# Generated by Django 6.0.2 on 2026-05-27 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_send', '0003_data_email_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Persona usuaria que disparó el envío', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
