# Generated by Django 6.0.2 on 2026-06-11 00:37

import django.db.models.deletion
import flow.upload_paths
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('group', models.CharField(choices=[('bp', 'Buenas prácticas'), ('cp', 'Cuestionario principal'), ('gen', 'Preguntas generales')], max_length=10, verbose_name='Grupo (flujo)')),
                ('public_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, help_text='https://vuetifyjs.com/en/styles/colors/', max_length=30, null=True)),
                ('icon', models.CharField(blank=True, help_text='https://fonts.google.com/icons', max_length=40, null=True)),
                ('order', models.IntegerField(default=4)),
                ('is_default', models.BooleanField(default=False, help_text='Status inicial de su grupo (uno por grupo)', verbose_name='Es status por defecto')),
                ('is_public', models.BooleanField(default=False, help_text='Los registros en este status se muestran en la página pública', verbose_name='Es público')),
                ('role', models.CharField(blank=True, choices=[('reviewer', 'Revisora'), ('ies', 'Institución')], help_text='Quién puede ejecutar las transiciones de salida; vacío = status terminal', max_length=10, null=True, verbose_name='Turno de')),
                ('requires_comment', models.BooleanField(default=False, help_text='Asignarlo exige escribir un comentario', verbose_name='Requiere comentario')),
                ('propagates_up', models.BooleanField(default=False, help_text='Al asignarse a un hijo, el padre también lo adopta', verbose_name='Propaga hacia arriba')),
                ('auto_on_first_save', models.BooleanField(default=False, help_text='Se asigna solo cuando la captura se guarda por primera vez', verbose_name='Automático al primer guardado')),
                ('applicable_models', models.ManyToManyField(blank=True, related_name='applicable_statuses', to='contenttypes.contenttype', verbose_name='Modelos donde aplica')),
                ('next_statuses', models.ManyToManyField(blank=True, related_name='previous_statuses', to='flow.status', verbose_name='Transiciones posibles')),
                ('valid_child_statuses', models.ManyToManyField(blank=True, help_text='Para mover el padre a este status, todos sus hijos deben estar en alguno de estos', related_name='valid_for_parent_statuses', to='flow.status', verbose_name='Status válidos de los hijos')),
            ],
            options={
                'verbose_name': 'Status de flujo',
                'verbose_name_plural': 'Status de flujo',
                'ordering': ['group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FlowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_events', to=settings.AUTH_USER_MODEL)),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='flow.status', verbose_name='Status anterior')),
                ('to_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='flow.status', verbose_name='Status nuevo')),
            ],
            options={
                'verbose_name': 'Evento de flujo',
                'verbose_name_plural': 'Eventos de flujo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=flow.upload_paths.resolve_upload_path, verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_attachments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, help_text='Evento con el que se adjuntó, si aplica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='flow.flowevent')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='flow_attach_content_3d299c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('group',), name='unique_default_per_group'),
        ),
        migrations.AddIndex(
            model_name='flowevent',
            index=models.Index(fields=['content_type', 'object_id'], name='flow_flowev_content_453982_idx'),
        ),
    ]
