# Generated by Django 6.0.2 on 2026-06-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='propagates_down',
            field=models.BooleanField(default=False, help_text='Al asignarse, todos los hijos también lo adoptan', verbose_name='Propaga hacia de arriba'),
        ),
    ]
