# Generated by Django 6.0.2 on 2026-06-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_status_propagates_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='entry_rules',
            field=models.JSONField(blank=True, default=list, help_text='Nombres de reglas del registry flowRules que deben cumplirse para mover un objeto a este status', verbose_name='Reglas de entrada (frontend)'),
        ),
        migrations.AddField(
            model_name='status',
            name='hint',
            field=models.TextField(blank=True, help_text='Guía de siguiente paso que el frontend muestra bajo el control de status; distinta de description (tooltip)', null=True, verbose_name='Sugerencia (frontend)'),
        ),
        migrations.AlterField(
            model_name='status',
            name='propagates_down',
            field=models.BooleanField(default=False, help_text='Al asignarse, todos los hijos también lo adoptan', verbose_name='Propaga hacia abajo'),
        ),
    ]
