# Generated by Django 6.0.2 on 2026-06-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_status_entry_rules_status_hint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='action_name',
            field=models.CharField(blank=True, help_text="Verbo del botón/menú que transiciona HACIA este status (p.ej. 'Enviar a revisión'); vacío si nunca es destino de una acción manual", max_length=255, null=True, verbose_name='Nombre de la acción'),
        ),
        migrations.AddField(
            model_name='status',
            name='content_editable',
            field=models.BooleanField(default=False, help_text='En este status, quien tiene el turno (role) puede editar valores; si no, solo puede transicionar', verbose_name='Contenido editable'),
        ),
        migrations.AlterField(
            model_name='status',
            name='public_name',
            field=models.CharField(help_text="Estado que muestra el chip (p.ej. 'Enviado')", max_length=255, verbose_name='Nombre del estado'),
        ),
    ]
