# Generated by Django 6.0.2 on 2026-06-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_status_action_name_status_content_editable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='confirm_text',
            field=models.TextField(blank=True, help_text='Cuerpo del diálogo de confirmación', null=True, verbose_name='Texto de confirmación'),
        ),
        migrations.AddField(
            model_name='status',
            name='confirm_title',
            field=models.CharField(blank=True, help_text='Encabezado del diálogo de confirmación; si está vacío el frontend deriva uno de action_name', max_length=255, null=True, verbose_name='Título de confirmación'),
        ),
        migrations.AddField(
            model_name='status',
            name='requires_confirmation',
            field=models.BooleanField(default=False, help_text='Antes de transicionar a este status, el frontend pide una confirmación explícita', verbose_name='Requiere confirmación'),
        ),
    ]
