# Generated by Django 6.0.2 on 2026-06-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_status_confirm_text_status_confirm_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='requires_comment',
        ),
        migrations.AddField(
            model_name='status',
            name='comment_prompt',
            field=models.CharField(blank=True, help_text='Etiqueta de la caja de comentario en el diálogo; vacío = el frontend usa un genérico', max_length=255, null=True, verbose_name='Rótulo del comentario'),
        ),
        migrations.AddField(
            model_name='status',
            name='comment_type',
            field=models.CharField(choices=[('none', 'Sin comentario'), ('optional', 'Opcional'), ('required', 'Obligatorio')], default='none', help_text='Si la transición a este status pide un comentario: ninguno, opcional u obligatorio', max_length=10, verbose_name='Comentario'),
        ),
    ]
