# Generated by Django 6.0.2 on 2026-07-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0006_remove_status_requires_comment_status_comment_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='priority',
            field=models.IntegerField(default=0, help_text='Urgencia para ordenar colecciones: mayor = más urgente, se muestra primero', verbose_name='Prioridad (urgencia)'),
        ),
    ]
