# Generated by Django 6.0.2 on 2026-07-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0007_status_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='hint_wait',
            field=models.TextField(blank=True, help_text='Variante del hint para el rol que NO tiene el turno (role); vacío = se muestra hint. Sin uso en terminales', null=True, verbose_name='Sugerencia en espera (frontend)'),
        ),
    ]
