# Generated by Django 6.0.2 on 2026-08-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0008_status_hint_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Descargable sin verificar la institución dueña', verbose_name='Público'),
        ),
    ]
