# Generated by Django 6.0.2 on 2026-04-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ies', '0006_invitationtoken_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscontrol',
            name='role',
            field=models.CharField(blank=True, choices=[('validator', 'Validador'), ('ies', 'Institución')], max_length=10, null=True, verbose_name='rol asociado'),
        ),
    ]
