# Generated by Django 6.0.2 on 2026-05-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ies', '0007_alter_statuscontrol_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Persona usuaria', 'verbose_name_plural': '1. Personas usuarias'},
        ),
    ]
