# Generated by Django 6.0.2 on 2026-06-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ies', '0008_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuscontrol',
            name='send_admin',
        ),
        migrations.RemoveField(
            model_name='statuscontrol',
            name='send_ies',
        ),
        migrations.RemoveField(
            model_name='statuscontrol',
            name='strict_ies',
        ),
        migrations.AddField(
            model_name='statuscontrol',
            name='can_send',
            field=models.BooleanField(default=False, help_text='Se puede enviar el paquete a la siguiente etapa', verbose_name='Puede enviarse'),
        ),
        migrations.AddField(
            model_name='statuscontrol',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Es status por defecto'),
        ),
    ]
