# Generated by Django 6.0.2 on 2026-06-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ies', '0009_remove_statuscontrol_send_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Institución', 'verbose_name_plural': 'Instituciones'},
        ),
    ]
