# Generated by Django 6.0.2 on 2026-07-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ies', '0010_alter_institution_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='submission_deadline',
            field=models.DateField(blank=True, help_text='Último día para enviar buenas prácticas; al día siguiente el periodo cierra solo.', null=True, verbose_name='Fecha límite de envío'),
        ),
    ]
