# Generated by Django 6.0.2 on 2026-08-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ies', '0011_period_submission_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='gen_submission_deadline',
            field=models.DateField(blank=True, help_text='Último día para enviar las preguntas generales; al día siguiente el periodo cierra solo.', null=True, verbose_name='Fecha límite de envío de generales'),
        ),
    ]
