# Generated by Django 6.0.2 on 2026-08-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ies', '0012_period_gen_submission_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Ve todas las secciones aunque no estén publicadas y no la detienen los cierres de periodo. Debe quedar fuera de cálculos, indicadores y exportes.', verbose_name='Institución de prueba'),
        ),
    ]
