# Generated by Django 6.0.2 on 2026-09-22 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0005_remove_observablecomment_observable_response_and_more'),
        ('example', '0009_remove_goodpractice_status_sending_and_more'),
        ('ies', '0013_institution_is_test'),
        ('survey', '0011_remove_axisvalue_status_register_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusControl',
        ),
    ]
