# Generated by Django 6.0.2 on 2026-09-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ies', '0014_delete_statuscontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='cp_open_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora desde la que las IES pueden responder el cuestionario por observable; vacío = aún no abre.', null=True, verbose_name='Apertura de respuestas del cuestionario principal'),
        ),
    ]
