# Generated by Django 6.0.2 on 2026-06-11 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
        ('survey', '0004_alter_populationquantity_number_men_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='axisvalue',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='flow.status'),
        ),
        migrations.AddField(
            model_name='generalgroupresponse',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='flow.status'),
        ),
    ]
