# Generated by Django 6.0.2 on 2026-06-25 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_status_action_name_status_content_editable_and_more'),
        ('survey', '0005_axisvalue_status_generalgroupresponse_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='flow.status')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_package', to='survey.survey')),
            ],
            options={
                'verbose_name': 'Envío de Preguntas Generales',
                'verbose_name_plural': 'Envíos de Preguntas Generales',
            },
        ),
        migrations.AddField(
            model_name='generalgroupresponse',
            name='general_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_group_responses', to='survey.generalpackage'),
        ),
    ]
