# Generated by Django 6.0.2 on 2026-06-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_generalgroup'),
        ('survey', '0006_generalpackage_generalgroupresponse_general_package'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='axisvalue',
            unique_together={('survey', 'axis')},
        ),
    ]
