# Generated by Django 6.0.2 on 2026-08-12 07:57

import django.db.models.deletion
from django.db import migrations, models


def backfill_is_present(apps, schema_editor):
    """La pertenencia al M2M pasa a ser `is_present=True` en la fila.

    Solo aplica a poblaciones (`is_main`) y a las 2 `is_standard_extra`;
    las autoridades se quedan en nulo porque su existencia nunca se
    capturó ahí. Si un sector estaba en el M2M sin fila, se crea.
    """
    Survey = apps.get_model('survey', 'Survey')
    PopulationQuantity = apps.get_model('survey', 'PopulationQuantity')
    surveys = Survey.objects.prefetch_related('sectors_legacy')
    for survey in surveys.iterator(chunk_size=200):
        sector_ids = [
            sector.id for sector in survey.sectors_legacy.all()
            if not sector.is_authority]
        if not sector_ids:
            continue
        updated = PopulationQuantity.objects.filter(
            survey=survey, sector_id__in=sector_ids).update(is_present=True)
        if updated == len(sector_ids):
            continue
        existing = set(PopulationQuantity.objects.filter(
            survey=survey, sector_id__in=sector_ids
        ).values_list('sector_id', flat=True))
        PopulationQuantity.objects.bulk_create([
            PopulationQuantity(
                survey=survey, sector_id=sector_id, is_present=True)
            for sector_id in sector_ids if sector_id not in existing])


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_generalquestion'),
        ('survey', '0008_alter_populationquantity_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='sectors',
            new_name='sectors_legacy',
        ),
        migrations.AddField(
            model_name='populationquantity',
            name='is_present',
            field=models.BooleanField(blank=True, null=True, verbose_name='Está presente'),
        ),
        migrations.AddField(
            model_name='populationquantity',
            name='number_non_binary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de personas no binarias'),
        ),
        migrations.AddField(
            model_name='survey',
            name='measures_non_binary',
            field=models.BooleanField(blank=True, null=True, verbose_name='Registra o mide población no binaria'),
        ),
        migrations.CreateModel(
            name='GeneralQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_apply', models.BooleanField(default=False, verbose_name='No Aplica')),
                ('general_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='question.generalquestion')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='survey.survey')),
            ],
            options={
                'verbose_name': 'Respuesta a pregunta general',
                'verbose_name_plural': 'Respuestas a preguntas generales',
                'unique_together': {('survey', 'general_question')},
            },
        ),
        migrations.RunPython(
            backfill_is_present, migrations.RunPython.noop),
    ]
