# Generated by Django 6.0.2 on 2026-08-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_rename_sectors_survey_sectors_legacy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Respuestas anuales de una IES', 'verbose_name_plural': 'Respuestas anuales de las IES'},
        ),
        migrations.DeleteModel(
            name='GeneralGroupAttachment',
        ),
    ]
