# Generated by Django 6.0.2 on 2026-09-22 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_alter_survey_options_delete_generalgroupattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='axisvalue',
            name='status_register',
        ),
        migrations.RemoveField(
            model_name='generalgroupresponse',
            name='status_register',
        ),
        migrations.DeleteModel(
            name='GeneralGroupComment',
        ),
    ]
