# Generated by Django 6.0.2 on 2026-09-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='Se genera del título si se deja vacío', max_length=120, unique=True, verbose_name='Identificador en la URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('file', models.FileField(blank=True, upload_to='public_documents/', verbose_name='Archivo')),
                ('generator', models.CharField(blank=True, choices=[('questionnaire_docx', 'Cuestionario en Word, generado desde la base')], default='', help_text='Si se indica, el archivo se genera al descargarlo', max_length=40, verbose_name='Generador')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('order', models.SmallIntegerField(default=5, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento público',
                'verbose_name_plural': 'Documentos públicos',
                'ordering': ['order', 'title'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('file', ''), models.Q(('generator', ''), _negated=True)), models.Q(models.Q(('file', ''), _negated=True), ('generator', '')), _connector='OR'), name='public_document_file_xor_generator')],
            },
        ),
    ]
